apiVersion: v1
kind: Service
metadata:
  name: assignment-8-service
spec:
  selector:
    app: assignment-8
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer # Hoặc NodePort nếu dùng Minikube/On-premise không có LB
